version: '2'
services:
  redis:
    restart: always
    image: redis
    ports:
      - '6379:6379'
  app:
    image: 'roulette:1.0.0'
    environment:
      - spring.redis.host=redis
    ports:
      - '8080:8080'
